name: envs
channels:
  - conda-forge
  - defaults
dependencies:
  - ipython
  - matplotlib
  - myst-parser
  - numpy
  - pandas
  - pip
  - pip:
    - codespell
    - mypy
    - ruff==0.14.11
  - pre-commit
  - pytest
  - scipy
  - sphinx
